server:
  port: 8888

spring:
  application:
    name: parking-management-system
  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.qztc.parkingmanagementsystem.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    paths-to-match: '/**'
    #生成文档所需的扫包路径，一般为启动类目录
    packages-to-scan: com.qztc.parkingmanagementsystem


#knife4j配置
knife4j:
  #是否启用增强设置
  enable: true
  setting:
    language: zh_cn
