server:
  port: 8888

spring:
  application:
    name: parking-management-system
  datasource:
    url: jdbc:mysql://localhost:3306/parking_management_system
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.qztc.parkingmanagementsystem.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
